include:
  - frontend/docker-compose.yml
  - product_service/docker-compose.yml
  - auth_service/docker-compose.yml
  #- docker/notification-service.yml
  #- docker/payment-service.yml
  - order_service/docker-compose.yml
  - user_service/docker-compose.yml
  #- docker/image-service.yml

services:
  api-gateway:
    container_name: api-gateway
    build: ./api_gateway
    ports:
      - "8080:8080"
    depends_on:
      - product-service
      - auth-service
      - user-service
      - order-service
      #- payment-service
      #- notification-service
      #- image-service
