include:
  - product-service/docker-compose.yml
  - docker/auth_service.yaml
  - docker/notification_service.yml
  - docker/payment_service.yml
  - docker/user_service.yml

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - product-service