spring.datasource.url=jdbc:postgresql://image-service-db:5432/image_service
spring.datasource.username=image_user
spring.datasource.password=app_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
