spring.application.name=product-service
server.port=8082

spring.datasource.url=jdbc:postgresql://product-db:5432/productdb
spring.datasource.username=app
spring.datasource.password=app_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

services.payment.url=http://payment-service:8080
